name: Run Server 24-7

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ALL dependencies
        run: |
          npm install socket.io express multer cors dotenv bcryptjs jsonwebtoken mongoose
          npm install

      - name: Run Server
        run: node server.js
